### ISSUE TITLE
Improve kompactWatch Syntax

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/jobmanagement#16]
```scala
KompactRef kompactWatch ActorRef // Confusing
ActorRef kompactWatch KompactRef // Better
```

**Comment by Bathtor** [comment]
To be fair, the intended semantics are still a "death watch" not a "kompact watch".
But I guess we are name-clashing on that? Any way around it?

**Comment by Max-Meldrum** [comment]
Will look into it.
